# Generated by Django 4.1.1 on 2022-09-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_extendeduser_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExtendedUser",
        ),
    ]
